MODEL:
  name: "deeplabv3"
  workspace: "workspace/gta5_sseg_pspnet_bare_trans"
SOLVER:
  image_per_batch: 2    # 8 for resnet34, and 5 for dense_block
  val_image_per_batch: 1

  optimizer: SGD
  base_lr: 1e-2
  weight_decay: 5e-4
  momentum: 0.9

  lr_scheduler: PolyLR
  lr_decay_step: 10
  lr_decay: 0.5
  max_iters: 40000
  power: 0.9
  # weight_decay: 0.0
  save_chkpt_each: 4000
  writer_sample_each: 1
  val_writer_sample_each: 1
  val_calc_each: 1000

