DATASETS:
  name: cityscapes
  split: ("train", "val")
  root: D:\Datasets\CityScapes
MODEL:
  name: "multi"
  workspace: "workspace/cityscapes_sseg_labelae"
SOLVER:
  image_per_batch: 1    # 8 for resnet34, and 5 for dense_block
  val_image_per_batch: 1
  base_lr: 5e-4
  lr_decay_step: 10
  lr_decay: 0.5
  weight_decay: 5e-4
  # weight_decay: 0.0
  save_chkpt_each: 1
  optimizer: Adam
  writer_sample_each: 1
  val_writer_sample_each: 1

